name: Build, push and deploy app
on: [push]

jobs:
  build_and_push_docker_image:
    name: Build and push to yc-cr
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        if: ${{ github.repository == 'alexseipopov/finance_backend' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main') }}
      - name: Yandex CR Login
        uses: yc-actions/yc-cr-login@v0.1-alpha
        if: ${{ github.repository == 'alexseipopov/finance_backend' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main') }}
        with:
          yc-sa-json-credentials: ${{ secrets.YC_KEY }}
      - name: Build image
        if: ${{ github.repository == 'alexseipopov/finance_backend' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main') }}
        env:
          CR_REGISTRY: crpo63gr16fshqrmielj
          CR_REPO: rmb_index_frontend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo $GITHUB_REPOSITORY
          echo $GITHUB_REF
          if [ "$GITHUB_REPOSITORY" == "alexseipopov/redisign_fronend" ] && [ "$GITHUB_REF" == "refs/heads/develop" ]; then
            docker build -t cr.yandex/$CR_REGISTRY/$CR_REPO:stand .
            docker push cr.yandex/$CR_REGISTRY/$CR_REPO:stand
          elif [ "$GITHUB_REPOSITORY" == "alexseipopov/redisign_fronend" ] && [ "$GITHUB_REF" == "refs/heads/main" ]; then
            docker build -t cr.yandex/$CR_REGISTRY/$CR_REPO:prod .
            docker push cr.yandex/$CR_REGISTRY/$CR_REPO:prod
          fi

  deploy:
    name: Deploy on server
    needs: build_and_push_docker_image
    runs-on: ubuntu-latest
    steps:
      - name: SSH connect and deploy
        uses: appleboy/ssh-action@master
        if: ${{ github.repository == 'alexseipopov/finance_backend' && github.ref == 'refs/heads/develop' }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          IMAGE_TAG: ${{ github.sha }}
          shell: bash
          script: |
            docker pull cr.yandex/crpo63gr16fshqrmielj/rmb_index_frontend:stand
            docker-compose up --no-deps -d frontend