name: Build, push and deploy app
on: [push]

jobs:
  build_and_push_docker_image:
    name: Build and push to yc-cr
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Yandex CR Login
        uses: yc-actions/yc-cr-login@v0.1-alpha
        with:
          yc-sa-json-credentials: ${{ secrets.YC_KEY }}
      - name: Build image
        env:
          CR_REGISTRY: crpo63gr16fshqrmielj
          CR_REPO: rmb_index_frontend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo $GITHUB_REPOSITORY
          echo $GITHUB_REF
          if [ "$GITHUB_REPOSITORY" == "alexsei_popov/redisign_frontend" ] && [ "$GITHUB_REF" == "refs/heads/develop" ]; then
            docker build -t cr.yandex/$CR_REGISTRY/$CR_REPO:stand .
            docker push cr.yandex/$CR_REGISTRY/$CR_REPO:stand
          fi

  deploy:
    name: Deploy on server
    needs: build_and_push_docker_image
    runs-on: ubuntu-latest
    steps:
      - name: SSH connect and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          IMAGE_TAG: ${{ github.sha }}
          script: |
            if [ "$GITHUB_REPOSITORY" == "alexsei_popov/redisign_frontend" ] && [ "$GITHUB_REF" == "refs/heads/develop" ]; then
              docker pull cr.yandex/crpo63gr16fshqrmielj/rmb_index_frontend:stand
              docker-compose up --no-deps -d frontend
            fi